# Generated by Django 4.0.2 on 2022-02-04 15:34

from django.db import migrations, models
import petstagram_workshop.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_petphoto_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='date_and_time_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[petstagram_workshop.main_app.validators.validate_file_max_size_in_mb]),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to='main_app.Pet'),
        ),
    ]
