# Generated by Django 4.0.2 on 2022-02-09 10:15

from django.db import migrations, models
import petstagram_workshop.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_petphoto_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='date_and_time_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[
                petstagram_workshop.common.validators.ValidateFileMaxSizeInMb(5)]),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to='main_app.Pet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11),
        ),
    ]
