# Generated by Django 4.0.2 on 2022-03-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.petphoto'),
            preserve_default=False,
        ),
    ]
